import { isApiRequest, proxyApiRequest } from "./api-proxy";
// @ts-expect-error: generated by `opennextjs-cloudflare build`; resolved by wrangler at bundle time
import openNextWorker from "../.open-next/worker.js";
// @ts-expect-error: same generated module. Re-exported so the durable-object classes the
// generated worker exports stay reachable if a cache override is configured later.
export * from "../.open-next/worker.js";

/**
 * MCL-63. The Cloudflare Worker entry, and the reason wrangler.jsonc points `main` here
 * rather than at `.open-next/worker.js`.
 *
 * The OpenNext CLI validates only open-next.config.ts, never the wrangler `main` field,
 * so wrapping its generated handler is supported: `opennextjs-cloudflare build` still
 * produces `.open-next/worker.js` and `.open-next/assets`, and wrangler bundles this
 * file around them.
 *
 * The split is the whole point. /api/* never reaches the Next route handlers in this
 * runtime - it is forwarded to the VPS backend that owns the database, which is where
 * MCL-48 put it. Everything else is the generated OpenNext handler, unchanged.
 *
 * This is the first of the two fail-closed guarantees; the second is the persistence
 * alias in next.config.ts, which makes an accidental local execution throw rather than
 * write a child's answer to a Worker-local filesystem.
 */

/** Only what this worker reads. Public configuration; never a secret. */
type WorkerEnv = { MCL_API_ORIGIN?: string };

const worker = {
  async fetch(request: Request, env: WorkerEnv, ctx: unknown): Promise<Response> {
    if (isApiRequest(new URL(request.url).pathname)) {
      return proxyApiRequest(request, env.MCL_API_ORIGIN);
    }

    return openNextWorker.fetch(request, env, ctx);
  },
};

export default worker;
